config/routes.rb
Rails.application.routes.draw do

  # eventually root 'main'
  # which will redirect to login if user is not logged in
  root 'users#logbook'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'
  get '/denied', :to => redirect('/access-denied.html')

  resources :flights do
    member do
      get :delete
    end
  end

  resources :logbook do
    member do
      get :delete
    end
  end

  resources :users do
    member do
        get :delete
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  has_one :logbook

  scope :sorted, lambda { order("id ASC") }

  EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i

  validates :first_name, :presence => true,
                         :length => { in: 2..25 }
  validates :first_name, :presence => true,
                         :length => { in: 2..50 }
  validates :email, :presence => true,
                    :length => { :maximum => 100 },
                    :format => EMAIL_REGEX,
                    :confirmation => true

  def name
    "#{first_name} #{last_name}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "admin"

  # before_action :confirm_logged_in, :only => [:show, :edit, :delete, :destroy]
  before_action :confirm_admin_logged_in, :only => [:index]
  # before_action :confirm_correct_user, :only => [:show, :edit, :delete, :destroy]
  before_action :only => [:show, :edit, :delete, :destroy] do
    confirm_correct_user(@user = User.find(params[:id]))
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = 'The wizard that lives in this website created the
      user successfully!'
      redirect_to(access_login_path)
    else
      render('new')
    end
  end

  def index
    #EXAMPLE OF USING THE LOGGER FOR DEBUGGING OR OTHER SHENANIGANS
    logger.debug("***** testing the logger ******")
    @users = User.sorted
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:notice] = 'The wizard that lives in the website successfully
      morphed the user! huzzah!'
      redirect_to(user_path(@user))
    else
    # 4) if save fails, redisplay the form so user can fix the problem(s)
    render('edit')
    end
  end

  def delete
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "The resident website wizard named Gondor the Lame
    destroyed '#{@user.name}' successfully with a powerful spell...it shan't
    be seen again!"
    redirect_to(users_path)
  end

  def logbook
    if session[:user_id]
      redirect_to(logbook_path(session[:user_id]))
    else
      redirect_to(access_login_path)
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :license_number,
      :licensing_agency,
      :email,
      :password,
      :admin,
      :last_log_in)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= error_messages_for(f.object) %>

<% AGENCY_LIST = ['Transport Canada', 'FAA', 'JAA'] %>

<table summary="User form fields">
  <tr>
    <th>First Name</th>
    <td><%= f.text_field(:first_name) %></td>
  </tr>
  <tr>
    <th>Last_name</th>
    <td><%= f.text_field(:last_name) %></td>
  </tr>
  <tr>
    <th>Email</th>
    <td><%= f.text_field(:email) %></td>
  </tr>
  <tr>
    <th>Password</th>
    <td><%= password_field_tag(:password) %></td>
  </tr>
  <tr>
    <th>License Number (if applicable)</th>
    <td><%= f.check_box(:license_number) %></td>
  </tr>
  <tr>
    <th>Licensing Agency (if licensed)</th>
    <td><%= f.select(:licensing_agency, AGENCY_LIST) %></td>
  </tr>
</table>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<% @page_title = "Edit Account" %>

<%= link_to("<< Account Details", user_path(@user), :class => 'back-link') %>

<div class="users edit">
  <h2>Edit Account</h2>

  <%= form_for(@user) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Edit User") %>
    </div>

  <% end %>
</div>

app/views/users/index.html.erb
<% @page_title = "All Users" %>

<div class="users index">
  <h2>Users</h2>
  <!-- 'action new' and similar refer to the actions defined in the
  UsersController -->
  <%= link_to("Add New User", new_user_path, :class => 'action new') %>

  <table class="listing" summary="User list">
    <tr class="header">
      <th class="center">#</th>
      <th class="center">Name</th>
      <th class="center">license number</th>
      <th class="center">Email</th>
      <th class="center">Admin?</th>
      <th class="center">Date account was created</th>
      <th class="center">options</th>
    </tr>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.first_name + ' ' + user.last_name %></td>
      <td><%= user.license_number %></td>
      <td><%= mail_to(user.email) %></td>
      <td class="center"><%= status_tag(user.admin) %></td>
      <td class="center"><%= user.created_at %></td>
      <td class="actions">
        <%= link_to("Show", user_path(user), :class => 'action show') %>
        <%= link_to("Edit", edit_user_path(user), :class => 'action edit') %>
        <%= link_to("Delete", delete_user_path(user), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/users/new.html.erb
<% @page_title = "Create New Account" %>

<%= link_to("<< log in", access_login_path, :class => 'back-link') %>

<div class="users new">
  <h2>Create User</h2>

  <%= form_for(@user) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Create User") %>
    </div>

  <% end %>
</div>

app/views/users/show.html.erb
<%= link_to("<< Back to List", users_path, :class => 'back-link')%>

<div class= "users show">
  <h2>Show user</h2>

  <table summary="user detail view">
    <tr>
      <th>Name</th>
      <td class="center"><%= @user.first_name + ' ' + @user.last_name %></td>
    </tr>
    <tr>
      <th>Email</th>
      <td class="center"><%= @user.email %></td>
    </tr>
    <tr>
      <th>License Number</th>
      <td class="center"><%= !@user.license_number.blank? ? @user.license_number : "none" %></td>
    </tr>
    <tr>
      <th>licensing_agency</th>
      <td class="center"><%= !@user.licensing_agency.blank? ? @user.licensing_agency : "none" %></td>
    </tr>
    <tr>
      <th>admin</th>
      <td class="center"><%= status_tag(@user.admin) %></td>
    </tr>    
    <tr>
      <th>Date account created</th>
      <td class="center"><%= @user.created_at %></td>
    </tr>
  </table>

</div>