config/routes.rb
Rails.application.routes.draw do

  # eventually root 'main'
  # which will redirect to login if user is not logged in
  root 'users#logbook'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'
  get '/denied', :to => redirect('/access-denied.html')

  resources :flights do
    member do
      get :delete
    end
  end

  resources :logbook do
    member do
      get :delete
    end
  end

  resources :users do
    member do
        get :delete
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  layout 'admin'

  before_action :confirm_logged_in, :except => [:login, :attempt_login, :logout]

  def menu
    # going to the database is expensive for page performance, so it's not
    # worth asking the database for just the username...
    @username = session[:username]
    @admin = session[:admin]
  end

  def login
    #login form doesnt need anything here
  end

  def attempt_login
    if params[:email].present? && params[:password].present?
      found_user = User.where(:email => params[:email]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
      end
    end

    if authorized_user
      session[:user_id] = authorized_user.id
      session[:username] = authorized_user.first_name + " " + authorized_user.last_name
      session[:admin] = authorized_user.admin
      flash[:notice] = "You are now logged in"
      redirect_to(admin_path)
    else
      flash.now[:notice] = "Invalid email/password combination"
      render('login')
    end
  end

  def logout
    session[:user_id] = nil
    session[:username] = nil
    flash[:notice] = 'logged out'
    redirect_to(access_login_path)
  end

  private

  def confirm_logged_in
    unless session[:user_id]
      flash[:notice] = "Please log in."
      redirect_to(access_login_path)
      # redirect_to is important (rather than render) because it prevents any other
      # actions from occuring
    end
  end
  
end

app/helpers/access_helper.rb
module AccessHelper
end

app/views/access/_form.html.erb
<%= error_messages_for(f.object) %>

<!-- <% AGENCY_LIST2 = ['Transport Canada', 'FAA', 'JAA'] %> -->

<table summary="User form fields">
  <tr>
    <th>First Name</th>
    <td><%= f.text_field(:first_name) %></td>
  </tr>
  <tr>
    <th>Last_name</th>
    <td><%= f.text_field(:last_name) %></td>
  </tr>
  <tr>
    <th>Email</th>
    <td><%= f.text_field(:email) %></td>
  </tr>
  <tr>
    <th>Password</th>
    <td><%= password_field_tag(:password) %></td>
  </tr>
  <tr>
    <th>License Number (if applicable)</th>
    <td><%= f.check_box(:license_number) %></td>
  </tr>
  <tr>
    <th>Licensing Agency (if licensed)</th>
    <td><%= f.select(:licensing_agency, AGENCY_LIST) %></td>
  </tr>
</table>

app/views/access/login.html.erb
<% @page_title = "Admin Menu" %>

<div class="login">
  <%= form_tag(access_attempt_login_path, :method => :post) do %>
  <table>
    <tr>
      <td><%= label_tag(:email) %></td>
      <td><%= text_field_tag(:email, params[:email]) %></td>
    </tr>
    <tr>
      <td><%= label_tag(:password) %></td>
      <td><%= password_field_tag(:password) %></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td><%= submit_tag("Log In") %></td>
    </tr>
  </table>
  <% end %>
</div>

app/views/access/menu.html.erb
<% @page_title = "Admin Menu" %>

<div class="menu">
  <h2>Admin Menu</h2>
  <div class="identity">Logged in as: <%= @username %><br>
                        Admin Status: <%= @admin %></div>
  <ul>
    <li><%= link_to("Manage Users", users_path) %></li>
    <li><%= link_to("logout", access_logout_path) %></li>
  </ul>
</div>