config/routes.rb
Rails.application.routes.draw do

  # eventually root 'main'
  # which will redirect to login if user is not logged in
  root 'users#logbook'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'
  get '/denied', :to => redirect('/access-denied.html')

  resources :flights do
    member do
      get :delete
    end
  end

  resources :logbook do
    member do
      get :delete
    end
  end

  resources :users do
    member do
        get :delete
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/logbook.rb
class Logbook < ApplicationRecord

  belongs_to :user
  has_many :flights

end

app/controllers/logbook_controller.rb
class LogbookController < ApplicationController
  layout 'admin'

  before_action do confirm_correct_user(@user = User.find(params[:id]))

  # these 8 items make up the core of CRUD (create read update delete)

  # these two are part of create
  def new
    @logbook = Logbook.new
  end

  def create
    # steps to save
    # 1) Instantiate a new object using input from the form
    @logbook = Logbook.new(logbook_params)
    # 2) Save the new object
    if @logbook.save
      # 3) if save succeeds, redirect user to desired page
      flash[:notice] = 'Logbook created successfully'
      redirect_to(logbook_path(@logbook))
    else
      # 4) if save fails, redisplay the form so user can fix the problem(s)
      @users = User.sorted
      render('new')
    end
  end

  def show
    @user = User.find(session[:user_id])
    @flight = Flight.new(flight_params)
  end

  # these are part of update
  # edit displays the form and update submits it to the db
  def edit
    @logbook = Logbook.find(params[:id])
  end

  def update
    # steps to update
    # 1) find a new object using input from the form
    @logbook = Logbook.find(params[:id])
    # 2) update the object
    if @logbook.update_attributes(logbook_params)
    # 3) if save succeeds, redirect user to desired page
      flash[:notice] = 'Logbook updated successfully'
      redirect_to(logbook_path(@logbook))
    else
      # 4) if save fails, redisplay the form so user can fix the problem(s)
      render('edit')
    end
  end

  # these are part of delete
  def delete
    @logbook = Logbook.find(params[:id])
  end

  def destroy
    @logbook = Logbook.find(params[:id])
    @logbook.destroy
    flash[:notice] = "Logbook for '#{@logbook.user.name}'
      deleted successfully"
    redirect_to(user_path(@logbook.user))
  end
end

  private

  def logbook_params
    params.require(:logbook).permit()
  end

  def flight_params
    params.require(:flight).permit(:date, :type, :ident, :pic,
      :sic, :single_engine?, :cross_country?, :dual_flight?, :day_hours,
      :night_hours, :sim_hours, :imc_hours, :hood_hours, :ifr_approaches,
      :route, :comments)
  end

end

app/helpers/logbook_helper.rb
module LogbookHelper
end

app/views/logbook/_add_flight_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Add flight form fields">
  <tr>
    <th>Date</th>
    <td><%= f.date_field(:date) %></td>
  </tr>
  <tr>
    <th>aircraft type</th>
    <td><%= f.text_field(:aircraft_type) %></td>
  </tr>
  <tr>
    <th>Ident</th>
    <td><%= f.text_field(:ident) %></td>
  </tr>
  <tr>
    <th>Pilot in Command</th>
    <td><%= f.text_field(:pic) %></td>
  </tr>
  <tr>
    <th>Co-Pilot/Second in Command</th>
    <td><%= f.text_field(:sic) %></td>
  </tr>
  <tr>
    <th>Type of Flight</th>
    <td><%= f.radio_button(:dual_flight, "true") %><%= label_tag(:single_engine_true, "Dual")%>
        <br><%= f.radio_button(:dual_flight, "false") %><%= label_tag(:single_engine_false, "Solo/PIC")%>
    </td>
  </tr>
  <tr>
    <th>Category of Plane</th>
    <td><%= f.radio_button(:single_engine, "true") %><%= label_tag(:single_engine_true, "Single_engine")%>
        <br><%= f.radio_button(:single_engine, "false") %><%= label_tag(:single_engine_false, "Multi-engine")%>
    </td>
  </tr>
  <tr>
    <th>Cross Country?</th>
    <td><%= f.check_box(:cross_country) %><%= label_tag(:cross_country,"") %></td>
  </tr>
  <tr>
    <th>Route</th>
    <td><%= f.text_field(:route) %></td>
  </tr>
  <tr>
    <th>Day Hours</th>
    <td><%= f.number_field(:day_hours, step: 0.1) %></td>
  </tr>
  <tr>
    <th>Night Hours</th>
    <td><%= f.number_field(:night_hours, step: 0.1) %></td>
  </tr>
  <tr>
    <th>Hood Hours</th>
    <td><%= f.number_field(:hood_hours, step: 0.1) %></td>
  </tr>
  <tr>
    <th>IMC Hours</th>
    <td><%= f.number_field(:imc_hours, step: 0.1) %></td>
  </tr>
  <tr>
    <th>Sim Hours</th>
    <td><%= f.number_field(:sim_hours, step: 0.1) %></td>
  </tr>
  <tr>
    <th># IFR Approaches</th>
    <td><%= f.number_field(:ifr_approaches, in: 1..20, step: 1) %></td>
  </tr>
  <tr>
    <th>Comments</th>
    <td><%= f.text_area(:comments, size: "100x10") %></td>
  </tr>
</table>

app/views/logbook/delete.html.erb
<h1>Logbook#delete</h1>
<p>Find me in app/views/logbook/delete.html.erb</p>

app/views/logbook/edit.html.erb
<h1>Logbook#edit</h1>
<p>Find me in app/views/logbook/edit.html.erb</p>

app/views/logbook/new.html.erb
<h1>Logbook#new</h1>
<p>Find me in app/views/logbook/new.html.erb</p>

app/views/logbook/show.html.erb
<div class= "logbook show">
  <h2>Logbook Summary</h2>

  <table summary="logbook summary">
    <tr>
      <th>Pilot</th>
      <td><%= @user.name %></td>
    </tr>
    <tr>
      <th>number of flights</th>
      <td><%= @user.logbook.flights.count %></td>
    </tr>
    <tr>
      <th>last update</th>
      <td><%= @user.logbook.updated_at %></td>
    </tr>
    <tr>
      <th>Links</th>
      <td class="actions">
        <%= link_to("Edit", edit_logbook_path(@user.logbook), :class => 'action edit') %>
        <%= link_to("Delete", delete_logbook_path(@user.logbook), :class => 'action delete') %>
      </td>
  </table>
  <div class="flight new">
    <h2>Create new flight</h2>

    <%= form_for(@flight) do |f| %>

      <%= render(:partial => 'add_flight_form', :locals => {:f => f}) %>

      <div class="form-buttons">
        <%= f.submit("Create Flight") %>
      </div>

    <% end %>
  </div>
  <table class="listing" summary="Flight list">
    <tr class="top header">
      <th class="center" colspan="6"></th>
      <th class="center" colspan="4">Single Engine</th>
      <th class="center" colspan="4">Multi Engine</th>
      <th class="center" colspan="4">Instrument</th>
      <th class="center" colspan="3">Cross Country</th>
      <th class="center" colspan="1"></th>
    </tr>
    <tr class="bottom header">
      <th class="center">#</th>
      <th class="center">Date</th>
      <th class="center">Type</th>
      <th class="center">Ident</th>
      <th class="center">PIC</th>
      <th class="center">SIC</th>
      <th class="center">Day PIC</th>
      <th class="center">Day DUAL</th>
      <th class="center">Night PIC</th>
      <th class="center">Night DUAL</th>
      <th class="center">Day PIC</th>
      <th class="center">Day DUAL</th>
      <th class="center">Night PIC</th>
      <th class="center">Night DUAL</th>
      <th class="center">Hood</th>
      <th class="center">IMC</th>
      <th class="center">Sim</th>
      <th class="center"># IFR Approaches</th>
      <th class="center">Day</th>
      <th class="center">Night</th>
      <th class="center">Route</th>
      <th class="center">Comments</th>
    </tr>
    <% @user.logbook.flights.each do |flight| %>
    <tr>
      <!-- ****** FLIGHT DETAILS ****** -->
      <td><%= flight.id %></td>
      <td><%= flight.date %></td>
      <td><%= flight.aircraft_type %></td>
      <td><%= flight.ident %></td>
      <td><%= flight.pic %></td>
      <td><%= flight.sic %></td>
      <!-- ****** FLIGHT HOURS ****** -->
      <!-- ****** SINGLE ENGINE ****** -->
        <!-- ****** DAY PIC ****** -->
      <td><%= !flight.dual_flight && flight.single_engine ? 0.0 : flight.day_hours %></td>
        <!-- ****** DAY DUAL ****** -->
      <td><%= !flight.dual_flight && flight.single_engine ? flight.day_hours : 0.0 %></td>
        <!-- ****** NIGHT PIC ****** -->
      <td><%= !flight.dual_flight && flight.single_engine ? 0.0 : flight.night_hours %></td>
        <!-- ****** NIGHT DUAL ****** -->
      <td><%= !flight.dual_flight && flight.single_engine ? flight.night_hours : 0.0 %></td>
      <!-- ****** MULTI ENGINE ****** -->
        <!-- ****** DAY PIC ****** -->
      <td><%= flight.dual_flight && !flight.single_engine ? 0.0 : flight.day_hours %></td>
        <!-- ****** DAY DUAL ****** -->
      <td><%= flight.dual_flight && !flight.single_engine ? flight.day_hours : 0.0 %></td>
        <!-- ****** NIGHT PIC ****** -->
      <td><%= flight.dual_flight && !flight.single_engine ? 0.0 : flight.night_hours %></td>
        <!-- ****** NIGHT DUAL ****** -->
      <td><%= flight.dual_flight && !flight.single_engine ? flight.night_hours : 0.0 %></td>
      <!-- ****** INSTRUMENT ****** -->
      <td><%= flight.hood_hours %></td>
      <td><%= flight.imc_hours %></td>
      <td><%= flight.sim_hours %></td>
      <td><%= flight.ifr_approaches %></td>
      <!-- ****** CROSS COUNTRY ****** -->
      <td><%= flight.cross_country ? flight.day_hours : 0.0 %></td>
      <td><%= flight.cross_country ? flight.night_hours : 0.0 %></td>
      <td><%= flight.route %></td>
      <td><%= flight.comments %></td>

    <% end %>
  </table>
</div>